### ISSUE TITLE
Support shortcuts?

### ISSUE THREAD

**Issue by amitbha** [amivaleo/Show-Desktop-Button#1]
refer to 'window demands attention shortcut' extension.

**Comment by amivaleo** [comment]
Apologies, I can't understanding what you mean.

There's no need to support shortcuts in this extension for showing/hiding the desktop. You can already configure the very same shortcut in gnome-control-center.

**Comment by amivaleo** [comment]
I noticed that the vanilla way to show the desktop works differetly than how this extension works.

I haven't discovered this method yet. Anyway, I finally added the shortcut you requested in v42. Sorry for taking so long...

Apologies to other users as well: #28 #42 #43
