### ISSUE TITLE
Clicking the show desktop button hides desktop icons (D-NG) and conky, even on version 7

### ISSUE THREAD

**Issue by raphaelc2009** [amivaleo/Show-Desktop-Button#10]
Hi,
I know you already had a lot of work with fixing the option for the location of the icon. However, I am experiencing another bug. With the new versions (5 and now 7), when I click on the button it "minimizes" even conky and the desktop icons (Desktop Icons - NG) and leaves me with a blank desktop. Do you think there would be any way to fix this ?
Thanks for your work on the extension.

**Comment by amivaleo** [comment]
Hi!

It's definitely feasible. The real issue is: how. 😅

But it's definitely something I want to fix.

**Comment by raphaelc2009** [comment]
Thanks

**Comment by raphaelc2009** [comment]
Looking at the code of other extensions, it seems possible to select only windows that show in the dock, but I haven't been able to get it to work on your extension, because I have almost no programing skills.

**Comment by raphaelc2009** [comment]
This is the piece of code I am trying to understand

`workspace = global.screen.get_active_workspace(),
    windows = workspace.list_windows().filter(function (w) {
        return w.get_window_type() !== Meta.WindowType.DESKTOP;
    });`

**Comment by amivaleo** [comment]
> Looking at the code of other extensions, it seems possible to select only windows that show in the dock, but I haven't been able to get it to work on your extension, because I have almost no programing skills.

Can you link those extensions here?

I'm aware there's a way. I saw something like that somewhere already.

**Comment by raphaelc2009** [comment]
This piece is from here https://github.com/l300lvl/Show-Desktop-Button/blob/master/show-desktop%40l300lvl.tk/extension.js

**Comment by raphaelc2009** [comment]
But I also saw that in gnome official alt tab js code, I'm going to send you a link

**Comment by amivaleo** [comment]
That `w.get_window_type()` is the key to fix this, I believe.

**Comment by raphaelc2009** [comment]
> That `w.get_window_type()` is the key to fix this, I believe.

Yes I thought so too

**Comment by raphaelc2009** [comment]
You can also take a look at that
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/altTab.js
This GNOME's official code for alt-tab

**Comment by raphaelc2009** [comment]
This is code from a extension which can show deskop

`function showDesktop() {

    const wspace = global.screen.get_active_workspace();

    const windows = wspace.list_windows();

    // These are the window types which should be minimized in ordder to show

    // the desktop. The window manager treats certain special entities, such as

    // the desktop UI, as windows, and we want to leave those out.

    // 

    // TODO: Is this list correct? I'm not sure what to do about things such as

    //       tooltips and combobox popups. We would ideally be able to hide them,

    //       but calling .minimize() makes it difficult for the user to restore

    //       them manually. If the user manually unminimizes some windows and

    //       shows the desktop again, then there will be no way of restoring

    //       these elements except through the console.

    const WINDOW_TYPES = [

        Meta.WindowType.NORMAL,

        Meta.WindowType.DIALOG,

        Meta.WindowType.MODAL_DIALOG,

        Meta.WindowType.SPLASHSCREEN

    ];



    // Find all of the suitable windows which we should minimize.

    let toMinimize = [];

    for (let i = 0; i < windows.length; ++i) {

        if (!windows[i].minimized) {

            const wtype = windows[i].get_window_type();

            if (WINDOW_TYPES.indexOf(wtype) > -1)

                toMinimize.push(windows[i]);

        }

    }

`

https://gitlab.com/eccheng/customcorner/-/blob/master/extension.js

**Comment by amivaleo** [comment]
This helps, and yet I need to know how to understand which "type" each window is. Also, I full list of all available types would be very useful.

Don't worry, I'll work on this. But not now unfortunately. -.-
I poured way too much alcohol on my laptop keyboard yesterday, and now I need to change it. -.-

**Comment by raphaelc2009** [comment]
Okay no problem

**Comment by raphaelc2009** [comment]
Hope you can find a new laptop

**Comment by raphaelc2009** [comment]
This should help

https://www.roojs.org/seed/gir-1.2-gtk-3.0/seed/Meta.WindowType.html

**Comment by amivaleo** [comment]
> Hope you can find a new laptop that suits you

What? No! 🙈️

My laptop is the best for me. I need the change the keyboard only, which I already ordered.

The external one that I'm using now is crappy.

**Comment by amivaleo** [comment]
> This should help
> 
> https://www.roojs.org/seed/gir-1.2-gtk-3.0/seed/Meta.WindowType.html

You're already much more skiled with me. :)

**Comment by raphaelc2009** [comment]
> > Hope you can find a new laptop that suits you
> 
> What? No! 🙈️
> 
> My laptop is the best for me. I need the change the keyboard only, which I already ordered.
> 
> The external one that I'm using now is crappy.

Oh that's great that you can change just the keyboard. Not so sure I could do it on my system76 laptop.

**Comment by amivaleo** [comment]
> system76

"island" keys?

Mine is a dell xps 13, with that type of keyboard. And yes, I can replace it.

**Comment by raphaelc2009** [comment]
> > system76
> 
> "island" keys?
> 
> Mine is a dell xps 13, with that type of keyboard. And yes, I can replace it.

yes it is a Lemur Pro so it is island keys but the keyboard is part of the top shelf with trackpad and palmrest.

**Comment by amivaleo** [comment]
And... Never clean that with alcohol soaked cotton...

**Comment by JuniorPolegato** [comment]
Hi!

I did that at the line 38 and it works for me:

if (windows[i].minimized || windows[i].get_window_type() == Meta.WindowType.DESKTOP) {

I added also at header stack:

const Meta = imports.gi.Meta;

**Comment by amivaleo** [comment]
> Hi!
> 
> I did that at the line 38 and it works for me (v7):
> 
> if (windows[i].minimized || windows[i].get_window_type() == Meta.WindowType.DESKTOP) {
> 
> I added also at header stack:
> 
> const Meta = imports.gi.Meta;

Thank you.

It looks like it works

I've added it to the repo files. 👍

**Comment by raphaelc2009** [comment]
Works perfectly!
Thanks a lot!

**Comment by amivaleo** [comment]
> Hi!
> 
> I did that at the line 38 and it works for me (v7):
> 
> if (windows[i].minimized || windows[i].get_window_type() == Meta.WindowType.DESKTOP) {
> 
> I added also at header stack:
> 
> const Meta = imports.gi.Meta;

This doesn't work on wayland.

**Comment by JuniorPolegato** [comment]
Hi!

Try this:

let ding = windows[i].wm_class == 'gjs' && windows[i].title.startsWith('@!') && windows[i].title.endsWith(';BDH');
if (windows[i].minimized || windows[i].get_window_type() == Meta.WindowType.DESKTOP || ding) {

**Comment by amivaleo** [comment]
> Hi!
> 
> Try this:
> 
> let wclass = windows[i].wm_class.toLowerCase();
> let wtitle = windows[i].title;
> let wtype = windows[i].window_type;
> let ding = wclass == 'gjs' && wtitle.startsWith('@!') && wtitle.endsWith(';BDH');
> let conky = wclass == 'conky';
> let desktop = wtype == Meta.WindowType.DESKTOP || wtype == Meta.WindowType.DOCK;
> if (windows[i].minimized || desktop || ding || conky) {

Not working.

I have to spend some time checking the best way to pick applications like conky or the gnome extension ding.

I have to dig here https://www.roojs.org/seed/gir-1.2-gtk-3.0/seed/Meta.Window.html

It will require some time.

Thank you for your help! It's really much appreciated :)

**Comment by JuniorPolegato** [comment]
For works fine.

I added this before "if":

// Type: 1 - Desktop | 2 - Dock
log(`${i}. class: ${wclass} - title: ${wtitle} - type: ${wtype}`);
log(`ding: ${ding} | conky: ${conky} | desktop: ${desktop}`);

On terminal, I run:

journalctl -f -o cat /usr/bin/gnome-shell

Then I get:

Screensaver: Locking.
0. class: conky - title: todo_conky - type: 2
ding: false | conky: true | desktop: true
1. class: conky - title: transparent_overlay - type: 0
ding: false | conky: true | desktop: false
2. class: conky - title: system_conky - type: 2
ding: false | conky: true | desktop: true
3. class: conky - title: system_conky - type: 2
ding: false | conky: true | desktop: true
4. class: gjs - title: @!0,27;BDH - type: 1
ding: true | conky: false | desktop: true
5. class: geany - title: extension.js - /home/junior/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo - Geany - type: 0
ding: false | conky: false | desktop: false
6. class: firefox - title: Clicking the show desktop button hides desktop icons (D-NG) and conky, even on version 7 · Issue #10 · amivaleo/Show-Desktop-Button - Mozilla Firefox - type: 0
ding: false | conky: false | desktop: false
7. class: skype - title: Skype - type: 0
ding: false | conky: false | desktop: false
8. class: gkrellm - title: gkrellm - type: 2
ding: false | conky: false | desktop: true
9. class: gnome-terminal - title: Terminal - type: 0
ding: false | conky: false | desktop: false
10. class: gkrellm - title: gkrellm_S-gateway - type: 0
ding: false | conky: false | desktop: false
11. class: telegramdesktop - title: Telegram - type: 0
ding: false | conky: false | desktop: false
Screensaver: LockButton was used.
Screensaver: Unlocking.
Screensaver: Updating Xautolock.

**Comment by amivaleo** [comment]
This is weird...

I will look at this tomorrow. Gotta sleep now. 😴

**Comment by amivaleo** [comment]
The latest edits in the repo should make the extension ignore DING at least.

This works for me on both wayland and xorg.

I have to test it with conky, which I haven't at all in my pc yet.

**Comment by amivaleo** [comment]
@JuniorPolegato,

may I ask you to test the extension as it is now in the repo and tell me if works as expected for you too, please?

**Comment by JuniorPolegato** [comment]
Hi! My dock panels are minimizing when I click on the house, so you need to add DESKTOP and DOCK types. Conky, when I lock the screen, switches from DESKTOP to DOCK the secondary windows and the main overlay window is NORMAL, so you need to be filtered by title as well.

**Comment by amivaleo** [comment]
> Hi! My dock panels are minimizing when I click on the house, so you need to add DESKTOP and DOCK types. Conky, when I lock the screen, switches from DESKTOP to DOCK the secondary windows and the main overlay window is NORMAL, so you need to be filtered by title as well.

This should be suffcient then, instead of the current `if` at line 54:

```
				if (windows[i].minimized ||
							windows[i].window_type == Meta.WindowType.DESKTOP ||
							windows[i].window_type == Meta.WindowType.DOCK !!
							windows[i].title.startsWith('DING') ||
							windows[i].wm_class.toLowerCase() == 'conky' ||
							( windows[i].title.startsWith('@!') && windows[i].title.endsWith('BDH') ) )
```

Right?

Can you test that?

**Comment by JuniorPolegato** [comment]
Ok. But: !! => ||

**Comment by amivaleo** [comment]
> Ok. But: !! => ||

:open_mouth: 

Yeah...

Me::monkey:

**Comment by amivaleo** [comment]
Uploaded to EGO review queue.

Thank you a lot.

**Comment by JuniorPolegato** [comment]
You're welcome!
