### ISSUE TITLE
allWindowsAreMinimized needs to be like panelButton

### ISSUE THREAD

**Issue by JuniorPolegato** [amivaleo/Show-Desktop-Button#15]
Hi!

allWindowsAreMinimized needs to bet outside of the function toggleDesktop, like this:

let panelButton;
let allWindowsAreMinimized = false;

**Comment by amivaleo** [comment]
Yes, already fixed in v11 which is in the release queue.

This is actually a duplicate for #14 ;)

Thank you a lot!
