### ISSUE TITLE
it works for a while after update

### ISSUE THREAD

**Issue by antonio24073** [amivaleo/Show-Desktop-Button#19]
ubuntu 20.04.1 LTS
64-bit
gnome 3.36.8

**Comment by amivaleo** [comment]
Hi!

Thank you for reporting this.

I need more info to debug this. In fact, the extension doesn't have any "time constraint", but it makes a few checks that have been causing several headaches to me...

I need you to tell me:
1- if you're using the [latest version available on ego](https://extensions.gnome.org/extension/1194/show-desktop-button/)

And I also need
2- you put here the output of this command
`$ journalctl -f -o cat /usr/bin/gnome-shell`
I need you to do this when you encounter this issue. Otherwise, the output is useless.

Thanks!

**Comment by antonio24073** [comment]
Hi, good morning,

The extension looks like this:
![image](https://user-images.githubusercontent.com/40250610/104124236-7d41d700-532e-11eb-8ef2-29259c8f996c.png)


When I click in green button, looks like this:
![image](https://user-images.githubusercontent.com/40250610/104124237-82068b00-532e-11eb-9dc8-432196335fc6.png)

And the button appears and works well:
![image](https://user-images.githubusercontent.com/40250610/104124241-86cb3f00-532e-11eb-8e85-c301acc21cb4.png)

But it stops to work some time later.

after reboot looks like:
![image](https://user-images.githubusercontent.com/40250610/104124252-8e8ae380-532e-11eb-8013-821a9cf86d10.png)
![image](https://user-images.githubusercontent.com/40250610/104124256-9480c480-532e-11eb-99b7-0fbff443b4eb.png)

and if I click in the green button works again.

I'm trying many extensions too. There are many logs and the flag -f doesn't works for this case because the problem occurs after reboot.

These is some logs that I found:
`
Usage of object.actor is deprecated for PanelMenuButton
get@resource:///org/gnome/shell/ui/environment.js:287:29
ShowDesktopButton@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:121:2
enable@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:214:2
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:349:26
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:234:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

Usage of object.actor is deprecated for PanelMenuButton
get@resource:///org/gnome/shell/ui/environment.js:287:29
ShowDesktopButton@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:145:2
enable@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:214:2
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:349:26
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:234:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

Usage of object.actor is deprecated for PanelMenuButton
get@resource:///org/gnome/shell/ui/environment.js:287:29
ShowDesktopButton@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:147:2
enable@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:214:2
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:349:26
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:234:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

Usage of object.actor is deprecated for PanelMenuButton
get@resource:///org/gnome/shell/ui/environment.js:287:29
ShowDesktopButton@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:149:2
enable@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:214:2
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:349:26
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:234:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 104]: Too many arguments to method Meta.Window.minimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 104]: Too many arguments to method Meta.Window.minimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 104]: Too many arguments to method Meta.Window.minimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 104]: Too many arguments to method Meta.Window.minimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 104]: Too many arguments to method Meta.Window.minimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 76]: Too many arguments to method Meta.Window.unminimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 76]: Too many arguments to method Meta.Window.unminimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 76]: Too many arguments to method Meta.Window.unminimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 76]: Too many arguments to method Meta.Window.unminimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 104]: Too many arguments to method Meta.Window.minimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 104]: Too many arguments to method Meta.Window.minimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 104]: Too many arguments to method Meta.Window.minimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 104]: Too many arguments to method Meta.Window.minimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 104]: Too many arguments to method Meta.Window.minimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 76]: Too many arguments to method Meta.Window.unminimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 76]: Too many arguments to method Meta.Window.unminimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 76]: Too many arguments to method Meta.Window.unminimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 76]: Too many arguments to method Meta.Window.unminimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 104]: Too many arguments to method Meta.Window.minimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 104]: Too many arguments to method Meta.Window.minimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 104]: Too many arguments to method Meta.Window.minimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 104]: Too many arguments to method Meta.Window.minimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 104]: Too many arguments to method Meta.Window.minimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 76]: Too many arguments to method Meta.Window.unminimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 76]: Too many arguments to method Meta.Window.unminimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 76]: Too many arguments to method Meta.Window.unminimize: expected 0, got 1
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js 76]: Too many arguments to method Meta.Window.unminimize: expected 0, got 1
Usage of object.actor is deprecated for SearchButton
get@resource:///org/gnome/shell/ui/environment.js:287:29
_init@/home/antonio/.local/share/gnome-shell/extensions/websearch@ciancio.net/extension.js:64:9
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
enable@/home/antonio/.local/share/gnome-shell/extensions/websearch@ciancio.net/extension.js:281:22
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
_onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:497:18
_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:496:11
Enable Multi Monitors Add-On (v21)...
Add Monitors ...
new: i1x3840y0w1366h768
pi:0
i:0 x:0 y:0 w:3840 h:2160
i:1 x:3840 y:0 w:1366 h:768
Usage of object.actor is deprecated for PanelMenuButton
get@resource:///org/gnome/shell/ui/environment.js:287:29
ShowDesktopButton@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:121:2
enable@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:214:2
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
_enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:612:22
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:611:37
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
_sync@resource:///org/gnome/shell/ui/sessionMode.js:198:14
popMode@resource:///org/gnome/shell/ui/sessionMode.js:166:14
_continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:502:30
deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:493:44
finish@resource:///org/gnome/shell/gdm/authPrompt.js:523:13
finish@resource:///org/gnome/shell/ui/unlockDialog.js:867:26
deactivate@resource:///org/gnome/shell/ui/screenShield.js:493:26
ScreenShield/</<@resource:///org/gnome/shell/ui/screenShield.js:110:57
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
_convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:169:19

Usage of object.actor is deprecated for PanelMenuButton
get@resource:///org/gnome/shell/ui/environment.js:287:29
ShowDesktopButton@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:145:2
enable@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:214:2
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
_enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:612:22
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:611:37
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
_sync@resource:///org/gnome/shell/ui/sessionMode.js:198:14
popMode@resource:///org/gnome/shell/ui/sessionMode.js:166:14
_continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:502:30
deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:493:44
finish@resource:///org/gnome/shell/gdm/authPrompt.js:523:13
finish@resource:///org/gnome/shell/ui/unlockDialog.js:867:26
deactivate@resource:///org/gnome/shell/ui/screenShield.js:493:26
ScreenShield/</<@resource:///org/gnome/shell/ui/screenShield.js:110:57
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
_convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:169:19

Usage of object.actor is deprecated for PanelMenuButton
get@resource:///org/gnome/shell/ui/environment.js:287:29
ShowDesktopButton@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:147:2
enable@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:214:2
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
_enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:612:22
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:611:37
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
_sync@resource:///org/gnome/shell/ui/sessionMode.js:198:14
popMode@resource:///org/gnome/shell/ui/sessionMode.js:166:14
_continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:502:30
deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:493:44
finish@resource:///org/gnome/shell/gdm/authPrompt.js:523:13
finish@resource:///org/gnome/shell/ui/unlockDialog.js:867:26
deactivate@resource:///org/gnome/shell/ui/screenShield.js:493:26
ScreenShield/</<@resource:///org/gnome/shell/ui/screenShield.js:110:57
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
_convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:169:19

Usage of object.actor is deprecated for PanelMenuButton
get@resource:///org/gnome/shell/ui/environment.js:287:29
ShowDesktopButton@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:149:2
enable@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:214:2
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
_enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:612:22
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:611:37
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
_sync@resource:///org/gnome/shell/ui/sessionMode.js:198:14
popMode@resource:///org/gnome/shell/ui/sessionMode.js:166:14
_continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:502:30
deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:493:44
finish@resource:///org/gnome/shell/gdm/authPrompt.js:523:13
finish@resource:///org/gnome/shell/ui/unlockDialog.js:867:26
deactivate@resource:///org/gnome/shell/ui/screenShield.js:493:26
ScreenShield/</<@resource:///org/gnome/shell/ui/screenShield.js:110:57
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
_convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:169:19
JS WARNING: [/home/antonio/.local/share/gnome-shell/extensions/Resource_Monitor@Ory0n/extension.js 106]: reference to undefined property "displayIcons"
loading user theme: /usr/share/themes/Yaru-dark/gnome-shell/gnome-shell.css
clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed
gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
JS ERROR: Extension show-desktop-button@amivaleo: TypeError: Gtk.IconTheme.get_default(...) is null
init@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:200:16
_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:433:50
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:346:27
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:599:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:574:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:608:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:257:22
start@resource:///org/gnome/shell/ui/main.js:146:5
@<main>:1:47
`


Antonio

**Comment by amivaleo** [comment]
There's definitely something wrong in these. To me, your system finds an error in line 214 in extension.js. That file is only 193 lines. 🤔️

I ask you to tell me what's the error you get from looking glass (`alt`+`F2`, then type `lg` and `enter`) when the extension is in this state:

![image](https://user-images.githubusercontent.com/40250610/104124236-7d41d700-532e-11eb-8ef2-29259c8f996c.png)

**Comment by antonio24073** [comment]
Hi again,

I don't know how copy from looking glass. I had to copy the error manually.

TypeError: GTK.IconTheme.get_default( ... ) is null.

I copy the extension folder too. In my computer the extension.js have the line 214.

[show-desktop-button@amivaleo.zip](https://github.com/amivaleo/Show-Desktop-Button/files/5793392/show-desktop-button%40amivaleo.zip)

Thanks for the dedication and readiness

Antonio

**Comment by amivaleo** [comment]
> Hi again,
> 
> I don't know how copy from looking glass. I had to copy the error manually.
> 
> TypeError: GTK.IconTheme.get_default( ... ) is null.
> 
> I copy the extension folder too. In my computer the extension.js has the line 214.
> 
> [show-desktop-button@amivaleo.zip](https://github.com/amivaleo/Show-Desktop-Button/files/5793392/show-desktop-button%40amivaleo.zip)
> 
> Thanks for the dedication and readiness
> 
> Antonio

That is an extremely old version of the extension. 🤔️
It doesn't even have the version numbering.

It must be because you're using gnome 3.36. I completely rewrote each file from anew in the last few months, when gnome 3.38 was already available, hence I tested the extension only on gnome 3.38. But I'm prone to say that it might work on gnome 3.36 too.

Try this:
1- delete all files and folders in `~/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/`,
2- download the latest version from here (or from EGO, they're the same),
3- paste these files in `~/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/`,
4- logout&login o reboot.

This should fix any issue. But let me know, please.

If it happens to works with no issues at all, I'll update the compatibility on EGO.

**Comment by antonio24073** [comment]
Hi,
Sorry, but I don't know what's EGO and didn't find in google.
I tried to install doing download from https://extensions.gnome.org/extension/1194/show-desktop-button/ with version 3.38.16 extracting and copying to extensions folder and doing logout. But after login it freezes the window and my computer does the logout again automatically. I was afraid that it crashes my gnome installation but after the second login all my extensions have been disabled. 

I tried again with all disabled. I believe that the command in your README from git for installation is git clone and not git remote add, so I clone to extensions folder and did logout login and it was like this:
![image](https://user-images.githubusercontent.com/40250610/104246471-d2700c80-5444-11eb-857c-648d00bcc5f4.png)

I enable it but nothing happened. After I try to click in green button and nothing happened again.

I think it is not compatible with gnome 3.36.8 . 

Thank you for have tried to help me.

**Comment by antonio24073** [comment]
here are some logs:
`
gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
JS ERROR: Extension show-desktop-button@amivaleo: TypeError: Gtk.IconTheme.get_default(...) is null
init@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:200:16
_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:433:50
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:346:27
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:599:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:574:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:608:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:257:22
start@resource:///org/gnome/shell/ui/main.js:146:5
@<main>:1:47

gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
JS ERROR: Extension websearch@ciancio.net: TypeError: theme is null
init@/home/antonio/.local/share/gnome-shell/extensions/websearch@ciancio.net/extension.js:273:5
_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:433:50
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:346:27
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:599:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:574:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:608:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:257:22
start@resource:///org/gnome/shell/ui/main.js:146:5
@<main>:1:47

`
`
gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
JS ERROR: Extension show-desktop-button@amivaleo: TypeError: Gtk.IconTheme.get_default(...) is null
init@/home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js:200:16
_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:433:50
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:346:27
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:599:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:574:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:608:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:257:22
start@resource:///org/gnome/shell/ui/main.js:146:5
@<main>:1:47
`

`JS ERROR: Could not load extension show-desktop-button@amivaleo: Error: Failed to load metadata.json: Gio.IOErrorEnum: Error opening file /home/antonio/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/metadata.json: Permission denied
createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:289:19
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:594:34
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:574:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:608:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:257:22
start@resource:///org/gnome/shell/ui/main.js:146:5
@<main>:1:47`

**Comment by antonio24073** [comment]
It works!!! 
First I had to enable the extensions in gnome tweaks because it was deactivated.
I didn't see that desktop icon because now it's in the right.
Thank you.

**Comment by amivaleo** [comment]
> I don't know what's EGO and didn't find in google

It's "Extensions Gnome Org", the usual [website](https://extensions.gnome.org).

> I believe that the command in your README from git for installation is git clone and not git remote add, so I clone to extensions folder

Ups! My bad, I'm gonna fix that git command.

> after login it freezes the window and my computer does the logout again automatically

Installing extensions as I told you here is a bit nasty indeed. I can't see other ways to debug them.

> desktop icon [...] now it's in the right.

Yeah, I changed the default position, but you can change that in the extension preferences.

> It works!!!

Good. Just play with it for a bit longer so to be sure it actually works fine.

Please come back here in the following days and tell me if this issue is to be considered fixed with the latest version of the extension. If so, I'll then add support for gnome 3.36. ;)

Thanks!

**Comment by amivaleo** [comment]
So, is everything alright now? Shall I close this and add support for gnome 3.36 to the current version of the extension?

**Comment by antonio24073** [comment]
Yes, alright. You can add 3.36 support but make sure that the extension button is from https://extensions.gnome.org/extension/1194/show-desktop-button/
is for the updated version because my problem was that it.
Thank you.

**Comment by amivaleo** [comment]
> Yes, alright. You can add 3.36 support but make sure that the extension button from https://extensions.gnome.org/extension/1194/show-desktop-button/
> is for the updated version because my problem was it.
> Thank you.

I'll try to get rid of all the old versions. I thought EGO let users download the latest release by default. 🤔️🤷‍♂️️

Thank you!
