### ISSUE TITLE
Not working in gnome 3.30.0

### ISSUE THREAD

**Issue by LinArcX** [amivaleo/Show-Desktop-Button#2]
distribiution: arch linux

**Comment by cbowman57** [comment]
> distribiution: arch linux

For 3.30 replace global.screen in extension.js with global.workspace_manager

**Comment by LinArcX** [comment]
@cbowman57 thank you. i update the pkgbuild in aur too.
https://aur.archlinux.org/packages/gnome-shell-extension-show-desktop-button/
