### ISSUE TITLE
Hiding the Desktop Icons extension overlay unexpectedly

### ISSUE THREAD

**Issue by proninyaroslav** [amivaleo/Show-Desktop-Button#24]
I'm using Desktop Icons extension to display icons on the desktop https://gitlab.com/rastersoft/desktop-icons-ng. When I click on the button, it hides not only windows, but also icons on the desktop.

**Comment by amivaleo** [comment]
Yes, I'm aware of this issue. I haven't time now to try and fix it. I've had very very busy days and weeks.

Thank you for reporting this. I can't promise any fix anytime soon unfortunately. :(

**Comment by proninyaroslav** [comment]
Fixed in https://github.com/amivaleo/Show-Desktop-Button/pull/25

**Comment by proninyaroslav** [comment]
@amivaleo 
I also asked Sergio to fix the minimization on the Desktop Icons side, to eliminate this bug in the future: https://gitlab.com/rastersoft/desktop-icons-ng/-/merge_requests/272

**Comment by amivaleo** [comment]
> @amivaleo
> I also asked Sergio to fix the minimization on the Desktop Icons side, to eliminate this bug in the future: https://gitlab.com/rastersoft/desktop-icons-ng/-/merge_requests/272

Thank you dude :)
I much appreciate this.
