### ISSUE TITLE
Support for GNOME 42 ubuntu 22.04

### ISSUE THREAD

**Issue by appleton252** [amivaleo/Show-Desktop-Button#26]
Hey,

This is a great extension and I consider it essential! 

Are their plans to support this for GNOME 42? Is it simple to make this compatible for GNOME 42?

Thank you,

**Comment by amivaleo** [comment]
Hi!

I can say there is the will to keep this extension alive. So yes, it will be updated so to work with gnome 42. I haven't checked anything for this issue yet, I can't say now if it is a matter of few changes or not.

**Comment by amivaleo** [comment]
Fixed.
I have to thank @xiaozhangup
