### ISSUE TITLE
Would It be possible to bind this to a keybind?

### ISSUE THREAD

**Issue by EmilyisWIP** [amivaleo/Show-Desktop-Button#28]
I don't see myself using mouse to hide the windows a lot, but I would really like to use Super+D :heart:

A way to change the state through a terminal command would be enought.

I don't like the default `hide all windows` option, because it doesn't transition smoothly

**Comment by amivaleo** [comment]
Hi!

I see this more a like a bug report for the default functionality rather than a feature request for this extension.

I have no plan to add a keyboard shortcut for this extension, since it'd be a "duplicated feature" in a sense. 🤔️

**Comment by EmilyisWIP** [comment]
Oh okay! Thanks for the reply anyway :heart:
