### ISSUE TITLE
Make a builtin extension?

### ISSUE THREAD

**Issue by nater1983** [amivaleo/Show-Desktop-Button#29]
How can we make this a built in extension instead of making it per user I would like to make it for all users....

**Comment by amivaleo** [comment]
Hi dear.

My apologies for the late reply. I was on vacation and had little to no access to internet, nor I had much time (and "will" 👀️) for checking emails.

I completely ignore the process that can make this a builtin extension. I have no contacts with other devs.

To my knowledge, basically all extentions are per user. There are only a few exceptions, which are those extension that can be installed using the distro package manager.

All these processes are unknown to me. And I honestly wonder if this extension worths the efforts needed to achieve what you suggest...
