### ISSUE TITLE
Add "center-left" to the settings

### ISSUE THREAD

**Issue by maxasix** [amivaleo/Show-Desktop-Button#33]
On GNOME 42, when the "Center" option is selected, the button is located on the left from date, rather than on the right.
The last April commit was the last commit that had the "Show Desktop" button located on the right from date. Now it's on the left without any option to change it back. Please give the option to locate the button either on the left or on the right from date.

**Comment by amivaleo** [comment]
Oh, gosh!
Thank you for this! I'll definitely fix this in the next update, which I'm going to release tomorrow (it's 22:20 for me).

Thanks. :)

**Comment by amivaleo** [comment]
Done. :)

I'm going to upload this in EGO.

**Comment by maxasix** [comment]
Thank you!
