### ISSUE TITLE
Call for translators

### ISSUE THREAD

**Issue by amivaleo** [amivaleo/Show-Desktop-Button#34]
Hi!

I would like to localize this extension into as many languages as possible.

I warmly ask you to submit translation files following the procedure in the README, or even by submitting a text file with all the translations of the strings inside the `show-desktop-button.pot` file.

Thank you!

**Comment by CuriousApe2020** [comment]
Since there isn't any complicated language involved, I would suggest to just translate it using DeepL?
deepl.com

**Comment by amivaleo** [comment]
> Since there isn't any complicated language involved, I would suggest to just translate it using DeepL? deepl.com

Yeah, I give it a try.
Thanks

**Comment by amivaleo** [comment]
I close this one, not because I don't want anymore help with translations but because I think this issue is not that vital here. :)
