### ISSUE TITLE
Estonian translation

### ISSUE THREAD

**Issue by meybonomme** [amivaleo/Show-Desktop-Button#41]
Estonian translation (language code et_EE)

[show-desktop-button.zip](https://github.com/amivaleo/Show-Desktop-Button/files/13044941/show-desktop-button.zip)

**Comment by amivaleo** [comment]
Thank you!

I'll include this tomorrow. I left my pc at work today... 🙄

**Comment by meybonomme** [comment]
You have done little mistake adding estonian translation.
Language code is `et_EE` not et_ET ;)
https://github.com/amivaleo/Show-Desktop-Button/tree/master/locale

**Comment by amivaleo** [comment]
Ups... Sorry. I'm fixing it.

**Comment by meybonomme** [comment]
And not ee_EE, right code is still `et_EE`. Please do copy-paste :smile: 

Language codes: https://www.venea.net/web/culture_code
`et-EE | Estonian (Estonia) | eesti (Eesti) | et | est | ETI | 1061 | et-EE`

**Comment by amivaleo** [comment]
That's embarrasing... Should have checked first. 😅

Fixing...

**Comment by meybonomme** [comment]
In most cases language and country codes are same. Example: Your home country is Italy and Italian (Italy) code is it_IT. But Estonian (Estonia) is one of exceptions - estonian language code is `et`, but country code is `EE`.

Estonia have independent country (again) since 1991 and country codes ES (Spain) and ET (Ethiopia) have already taken. That's why Estonian country code is EE and why language and country codes are different ;)

**Comment by amivaleo** [comment]
> In most cases language and country codes are same.

Yeah, I am aware of that. I was just... You know, I gave it for granted that this was not an exception and... Didn't check to make sure of that. 🫢

Sorry...

**Comment by meybonomme** [comment]
Translation also tested and it works, but "Position" string is not translatable:

![Screenshot from 2023-10-21 00-40-11](https://github.com/amivaleo/Show-Desktop-Button/assets/147217565/27964e45-144d-4c05-bda9-cfdf7615049d)

I don't know is it possible also translate extension name and description?

![Screenshot from 2023-10-21 00-40-47](https://github.com/amivaleo/Show-Desktop-Button/assets/147217565/0532335b-1c18-463a-ba3f-49ef9195b090)

**Comment by amivaleo** [comment]
This... I can't reproduce it. o.O

![image](https://github.com/amivaleo/Show-Desktop-Button/assets/24316547/59c6f0c9-e641-4310-bd8a-e10a153fff6a)

**Comment by amivaleo** [comment]
I checked this in a virtual machine. I could reproduce the issue and already fixed it by updating all translations. Thank you!

**Comment by meybonomme** [comment]
I can't see "position" string in pot file :)

**Comment by amivaleo** [comment]
But it's there. 👀

The latest pot file I updated today has it.

**Comment by meybonomme** [comment]
Estonian is one of the most difficult languages in the world, every AI- or machine translations to estonian are very ugly and have many grammar errors. Nice and correct world in estonian is "Asukoht" (Position) :slightly_smiling_face:

**Comment by amivaleo** [comment]
Now I see why devs tend to have this beahviour of telling people to do the work and then hand it over.

My desire to help by doing the job by myself leads to need to re-do the same thing several times. 😄

Fixed it (hopefully!).
