### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by tpaniaki** [amivaleo/Show-Desktop-Button#42]
Is there a way to create a keyboard shortcut to trigger the extension?

**Comment by amivaleo** [comment]
Hi,

no, but there's no need for that.
Default gnome settings come with a shortcut for hiding open windows.

You can find it in Settings > Keyboard > View and set keyboard shortcut > Navigation > "Hide all normal windows".

(I translated from my native language. Labels might have a slightly different name).

You can set a shortcut there.
