### ISSUE TITLE
Please add support for GNOME 46

### ISSUE THREAD

**Issue by tomikaka22** [amivaleo/Show-Desktop-Button#46]
GNOME 46 has been available on Arch and Fedora Linux for a while now, and other more stable distros are starting to adapt it too.

I would like to ask for an update to the extension so that it can be used on GNOME 46.

**Comment by amivaleo** [comment]
Hi!

The code here is ready for gnome 46, but I want to put my hands on gnome 46 before releasing it on EGO website. That will happen in this month, after I get Fedora 40 on my pc. ;)

**Comment by amivaleo** [comment]
Update for gnome 46 in review queue on EGO. ;)
