### ISSUE TITLE
Incompatibility reported on GNOME Shell extensions site

### ISSUE THREAD

**Issue by imliuyzh** [amivaleo/Show-Desktop-Button#48]
I understand this extension is compatible with GNOME 46 from README. However, GNOME's website said otherwise:

![](https://github.com/amivaleo/Show-Desktop-Button/assets/50005255/39ace590-9435-46d5-8dbc-f2cbc7d0edcd)

**Comment by amivaleo** [comment]
The updated extension is in the review queue on that website. I put it there less than 10 hours ago.
A reviewer has to approve it and then it becomes available for everyone.

It's just a matter of some patience while waiting for the reviewer. :)
