### ISSUE TITLE
Not working on Ubuntu 18.04.3 LTS, GNOME 3.28.2

### ISSUE THREAD

**Issue by leitor69** [amivaleo/Show-Desktop-Button#5]
Nothing happens when I click on icon.

**Comment by ldecoster** [comment]
I have the same problem with Ubuntu 18.04.3 and Gnome 3.28.4.
If you need any other information, I can provide them to you.

Could you please update your extension ?

**Comment by leitor69** [comment]
If the Gnome version is less than 3.30 then replace   global.workspace_manager   by   global.screen  in the file ~/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/extension.js
