### ISSUE TITLE
Unlinked prefs to extension

### ISSUE THREAD

**Issue by amivaleo** [amivaleo/Show-Desktop-Button#51]
Hi @jrahmatzadeh ,

I would like to get some help from you here.

I am struggling to fix the prefs in this "experimental" branch. The gschema is not loaded in dconf, and the prefs seem to be unlinked to extension.js. 🤔

Thank you!

**Comment by jrahmatzadeh** [comment]
`settings.bind()` in `prefs.js` won't work since the `indicator-position` is enum in your schemas file and you are trying to save it as integer.

I recommend using this instead of that:

```js
indicatorPosition.set_selected(settings.get_enum('indicator-position'));

indicatorPosition.connect('notify::selected', () => {
    settings.set_enum('indicator-position', indicatorPosition.selected);
});
```

**Comment by amivaleo** [comment]
But... How do you learn that? :(

I've been checking for answers in the other extensions I have installed, but all of them seem to do something different. :|

Anyway... Thanks. :)
I'll work on this this evening (it's 8:30 am here), after work, hopefully. ^_^

**Comment by amivaleo** [comment]
Thank you a lot. :)

I joined the room but... I think it will take a lot before I pubblicly write something there. I feel like I could ask VERY stupid questions... 🥺

Anyway, newer version of this extension is coming! :D

**Comment by jrahmatzadeh** [comment]
No problem at all. We have many friendly people in the Matrix room. Feel free to ask any questions there.
