### ISSUE TITLE
With Papirus icon theme custom icon is always light

### ISSUE THREAD

**Issue by meybonomme** [amivaleo/Show-Desktop-Button#52]
With Papirus icon theme custom icon is always light, not dark as expected:

![Screenshot From 2024-11-01 09-25-38](https://github.com/user-attachments/assets/539891f2-52de-4697-afa6-7daf7091bb30)

If I load the desired icon directly from the code by changing the extension.js line from `icon_name: Settings.get_string('indicator-icon-name').split('/').pop(),` to `icon_name: 'user-desktop-symbolic'` then correct and dark icon is loaded:

![Screenshot From 2024-11-01 09-26-56](https://github.com/user-attachments/assets/b8177809-4cb9-4746-8d71-9d5db25e6911)

**Comment by amivaleo** [comment]
Ouch.

You're right.

This can be fixed by replacing that very same line with the following:

`icon_name: Settings.get_string('indicator-icon-name').split('/').pop().replace(/\.[^/.]+$/, ''),`

I am on my way to upload this fix.

Thank you :)
