### ISSUE TITLE
Request: Remove the feature where the button shows all apps on the 2nd click

### ISSUE THREAD

**Issue by tommytran732** [amivaleo/Show-Desktop-Button#6]
First of all, thank you for making this extension :) It does help make GNOME more tolerable and easier to use.

What I really do not like about the extension is the fact that it shows all running apps when the user clicks it the second time. I think it should only minimize all apps like how the show desktop button works on Windows. It is quite annoying when I click on the button expecting to return to my desktop and it just opened up more apps instead. It would be nice if this behavior could be disabled.

**Comment by amivaleo** [comment]
Uhm...

I think this was the original behaviour, which I didn't like. 😄

But I might change my mind. I'll definitely reconsider this. Thanks.
