### ISSUE TITLE
"Error" status for extension after reboot - Fedora 32

### ISSUE THREAD

**Issue by jeffrussell37** [amivaleo/Show-Desktop-Button#8]
When the extension is first installed in Fedora 32, it works until the next reboot.  After reboot, the button no longer exists.  Navigating to the gnome extensions page, it displays the "Error" button.  Disabling and re-enabling does not resolve the issue.  Only an uninstall of the extension and subsequent reinstall resolves the issue.

**Comment by amivaleo** [comment]
Can you please show me what Looking Glass says after the reboot?

You can access Looking Glass by `alt`+`F2`, then type "lg" and press `enter`. In the new window, click on "Extensions", look for the extension and show the errors.

Thanks!

**Comment by jeffrussell37** [comment]
Sure thing!.  First time using "lg".  The error recorded is "Gtk.IconTheme.get_default() is null"
Please let me know if you need anything further, and thank you for looking into it!

**Comment by amivaleo** [comment]
> Sure thing!. First time using "lg". The error recorded is "Gtk.IconTheme.get_default() is null"
> Please let me know if you need anything further, and thank you for looking into it!

Which distro are you using?

I can't replicate the issue but maybe...

1 Go to `~/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo`
2 and open `extension.js`
3 then add `const Gtk = imports.gi.Gtk;` as first line in that text file
4 save and restart the shell (`alt`+`F2`, then type `r` and then give `enter` in xorg, otherwise logout&login)

This could fix the issue. Not sure. Probably not I believe... But it worth trying.

**Comment by jeffrussell37** [comment]
I'm using Fedora 33 as of yesterday.  :)  I was using Fedora 32 up to that time.
I'll give your suggestion a shot and get back to you.  Thank you,

Jeff

**Comment by amivaleo** [comment]
Pretty weird.

I've just started fixing the extension for fedora 33, which is also my distro. But I got a completely different issue. 😅

**Comment by jeffrussell37** [comment]
And I just checked that file, and the line you suggested I add is already there on line 3.

**Comment by amivaleo** [comment]
I guess I haven't updated the repo here for a long time, while I kept editing my personal version locally.

I'm working on this extension and I'm trying to add the feature requested in #6 .
I'll update the files here in the following days. Maybe today...? And I'll submit the new version on EGO.

**Comment by jeffrussell37** [comment]
Sounds good, sir!

**Comment by amivaleo** [comment]
I've just uploaded a completely new version of this extension.
It works on my computer, fedora 33. I'd prone to add "flawlessly" but... I don't want to rush.

Would you like to test this, Jeff? It'd help a lot.

If so, download the entire repo, unzip it, and replace ALL files in `~/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo` with them. Then restart the shell or logout&login.

**Comment by jeffrussell37** [comment]
Hey, I'm game!  Downloading now...

**Comment by amivaleo** [comment]
> There is still a small issue with the configuration of the button location. No matter which is selected (left/center/right), it always goes to the right. Do you want me to open another issue for that?

Nope. I dropped that feature. I don't want to add icons nowhere else than on the right. So... No issue for that.

I might change my mind on this in the future. But as for now, nope.

Anyway, you shouldn't be able to open any settings for this app. I guess you didn't login&logout but only restarted the shell or whatever.

> It works now!

Good. Thanks!
I close this. 😉

**Comment by jeffrussell37** [comment]
Thanks for the work on this!  I really appreciate it!
